[build]
  command = "export GATSBY_COMMIT_REF=$COMMIT_REF && export GATSBY_BRANCH=$BRANCH && export GATSBY_LAST_BUILD=$(date --iso-8601=seconds) && cd functions && npm install && npm run build && cd .. && npm install && npm run build"
  publish = "public"
  functions = "functions/dist"

[dev]
  command = "npm run develop"
  functions = "functions/dist"

[[plugins]]
package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
  mode = 'suffix'

[[redirects]]
from = "https://staging--squawk-market.netlify.app/*"
to = "https://staging.squawk-market.com"
status = 200
force = true
