import { IFeedConfigItem } from "../interfaces/IFeedConfigItem";

export const feedConfig: Array<IFeedConfigItem> = [
  {
    title: "Market Wide News",
    subtitle: "A medley of news from the entire market.",
    feedName: "market-wide",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "Economic Prints",
    subtitle:
      "Federal reserve press conferences, economic reports, inventories, etc.",
    feedName: "economic-prints",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Option Flows",
    subtitle:
      "Gamma, Vanna, and Charm exposures, as well as put / call ratios and put / call walls.",
    feedName: "option-flows",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "U.S. Bond Auctions",
    subtitle: "Auction results for U.S. Treasury bonds.",
    feedName: "us-bond-auctions",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Currencies",
    subtitle: "News, volume, price, and option action on the major currencies.",
    feedName: "currencies",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "SPX",
    subtitle: "News, volume, price, and option action on the SPX index.",
    feedName: "spx",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "SPY",
    subtitle: "News, volume, price, and option action on the SPDR S&P 500 ETF.",
    feedName: "spy",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "QQQ",
    subtitle:
      "News, volume, price, and option action on the Invesco QQQ Trust.",
    feedName: "qqq",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "IWM",
    subtitle:
      "News, volume, price, and option action on the iShares Russell 2000 ETF.",
    feedName: "iwm",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "BTC",
    subtitle: "Bitcoin price action and news.",
    feedName: "btc",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "ETH",
    subtitle: "Ethereum price action and news.",
    feedName: "etc",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "TSLA",
    subtitle: "Tesla - apparently everyone's favorite stock.",
    feedName: "tsla",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Unusual Trading Volume",
    subtitle: "Stocks, ETFs, and instruments with unusual trading volume.",
    feedName: "unusual-trading-volume",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "Most volatile",
    subtitle: "Instruments with a high percentage change in price today.",
    feedName: "move-volatile",
    isPopular: true,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "Most Active",
    subtitle: "Stocks, ETFs, and instruments with the most trading volume.",
    feedName: "most-active",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "New Highs",
    subtitle: "Instruments reaching new 52 week highs.",
    feedName: "new-highs",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "New Lows",
    subtitle: "Instruments reaching new 52 week lows.",
    feedName: "new-lows",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "Overbought",
    subtitle: "Instruments overbought according to RSI(14).",
    feedName: "overbought",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "Oversold",
    subtitle: "Instruments oversold according to RSI(14).",
    feedName: "oversold",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "Top Gainers",
    subtitle: "Instruments with a high percentage gain.",
    feedName: "top-gainers",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "Top Losers",
    subtitle: "Instruments with a high percentage loss.",
    feedName: "top-losers",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: false,
  },
  {
    title: "Unusual Options Volume",
    subtitle: "Stocks, ETFs, and instruments with unusual options volume.",
    feedName: "unusual-options-volume",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },

  {
    title: "Top Insider Buying",
    subtitle: "Stocks and ETFs with large amounts of insider buying.",
    feedName: "insider-buying",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Top Insider Selling",
    subtitle: "Stocks and ETFs with large amounts of insider selling.",
    feedName: "insider-selling",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Upcoming Earnings",
    subtitle: "Companies with upcoming earnings, expected earnings, and moves.",
    feedName: "upcoming-earnings",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Earnings Reports",
    subtitle: "Earnings reports and significant moves after earnings.",
    feedName: "earnings-reports",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Analysts - All",
    subtitle:
      "Latest institutional upgrades, downgrades, initiations, reiterations, and resumes.",
    feedName: "analysts-all",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Analyst Upgrades",
    subtitle: "Stocks that have received analyst upgrades.",
    feedName: "analyst-upgrades",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Analyst Downgrades",
    subtitle: "Stocks that have received analyst downgrades.",
    feedName: "analyst-downgrades",
    isPopular: false,
    hasSymbolInput: false,
    isComingSoon: true,
  },
  {
    title: "Custom",
    subtitle: "Track desired information for a specific instrument.",
    feedName: "custom",
    isPopular: false,
    hasSymbolInput: true,
    isComingSoon: true,
  },
];
